name: workflows, Jobs, and Steps

on:
    workflow_dispatch:

jobs:
    job-1:
        runs-on: unbuntu-24.04
        steps:
            - run: echo "This is Job 1, Step 1"
            - run: echo "This is Job 1, Step 2"
    job-2:
        runs-on: unbuntu-24.04
        steps:
            - run: echo "This is Job 2, Step 1"
    job-3:
        runs-on: unbuntu-24.04
        needs:
            - job-1
            - job-2
        steps:
            - run: echo "They aca also depend on one another..."
    job-4:
        runs-on: unbuntu-24.04
        needs: 
            - job-2
            - job-3
        steps:
            - run: echo "...to form a directed acyclic graph (DAG)"