name: run2
on:
    push:
        branches: [ '**' ]
    pull_request:
        branches: [ '**' ]
jobs:
    run2:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Hello World from run2!2️⃣"